(deftheme Custom Light
  "Created 2022-07-22.")

(custom-theme-set-variables
 'Custom Light
 '(ansi-color-faces-vector [default default default italic underline success warning error])
 '(ansi-color-names-vector ["#d2ceda" "#f2241f" "#67b11d" "#b1951d" "#3a81c3" "#a31db1" "#21b8c7" "#655370"])
 '(company-idle-delay 0.02)
 '(compilation-always-kill t)
 '(compilation-ask-about-save nil)
 '(compilation-auto-jump-to-first-error nil)
 '(compilation-max-output-line-length nil)
 '(compilation-scroll-output t)
 '(custom-safe-themes '("fa2b58bb98b62c3b8cf3b6f02f058ef7827a8e497125de0254f56e373abee088" "ce17f0b935cb4cf9167b384c8fefcff5448f039b89dbd1e45029400bc52b9b33" "bffa9739ce0752a37d9b1eee78fc00ba159748f50dc328af4be661484848e476" default))
 '(display-line-numbers-type 'visual)
 '(evil-want-Y-yank-to-eol t)
 '(explicit-shell-file-name "/usr/bin/fish")
 '(git-gutter:diff-option "-w")
 '(hl-todo-keyword-faces ''(("TODO" . "#dc752f") ("NEXT" . "#dc752f") ("THEM" . "#2d9574") ("PROG" . "#3a81c3") ("OKAY" . "#3a81c3") ("DONT" . "#f2241f") ("FAIL" . "#f2241f") ("DONE" . "#42ae2c") ("NOTE" . "#b1951d") ("KLUDGE" . "#b1951d") ("HACK" . "#b1951d") ("TEMP" . "#b1951d") ("FIXME" . "#dc752f") ("XXX+" . "#dc752f") ("\\?\\?\\?+" . "#dc752f")))
 '(ispell-dictionary "american")
 '(org-fontify-done-headline nil)
 '(org-fontify-todo-headline nil)
 '(package-selected-packages '(eshell-git-prompt gerrit shfmt reformatter insert-shebang helm-gtags ggtags flycheck-bashate fish-mode counsel-gtags counsel swiper ivy company-shell fira-code-mode symon-lingr ox-gfm org-re-reveal dockerfile-mode docker tablist json-mode docker-tramp aio json-snatcher minimap nov esxml kv unkillable-scratch persistent-scratch yasnippet-snippets xterm-color vterm treemacs-magit terminal-here smeargle shell-pop multi-term lsp-ui lsp-treemacs lsp-origami origami helm-lsp lsp-mode helm-ls-git helm-git-grep helm-company helm-c-yasnippet gitignore-templates git-timemachine git-modes git-messenger git-link fuzzy forge yaml markdown-mode magit ghub closql emacsql-sqlite emacsql treepy magit-section git-commit with-editor transient flyspell-correct-helm flyspell-correct flycheck-pos-tip pos-tip eshell-z eshell-prompt-extras esh-help company auto-yasnippet yasnippet auto-dictionary ac-ispell auto-complete ws-butler writeroom-mode visual-fill-column winum volatile-highlights vi-tilde-fringe uuidgen undo-tree queue treemacs-projectile treemacs-persp treemacs-icons-dired treemacs-evil treemacs cfrs pfuture posframe toc-org symon symbol-overlay string-inflection string-edit spaceline-all-the-icons memoize spaceline powerline restart-emacs request rainbow-delimiters quickrun popwin persp-mode password-generator paradox spinner overseer org-superstar open-junk-file nameless multi-line shut-up macrostep lorem-ipsum link-hint inspector info+ indent-guide hungry-delete hl-todo highlight-parentheses highlight-numbers parent-mode highlight-indentation hide-comnt helm-xref helm-themes helm-swoop helm-purpose window-purpose imenu-list helm-projectile helm-org helm-mode-manager helm-make helm-flx helm-descbinds helm-ag google-translate golden-ratio flycheck-package package-lint flycheck pkg-info epl flycheck-elsa flx-ido flx fancy-battery eyebrowse expand-region evil-visualstar evil-visual-mark-mode evil-unimpaired evil-tutor evil-textobj-line evil-terminal-cursor-changer evil-surround evil-numbers evil-nerd-commenter evil-mc evil-matchit evil-lisp-state evil-lion evil-indent-plus evil-iedit-state evil-goggles evil-exchange evil-escape evil-ediff evil-easymotion evil-collection annalist evil-cleverparens smartparens evil-args evil-anzu anzu eval-sexp-fu emr iedit clang-format projectile paredit list-utils elisp-slime-nav elisp-def f editorconfig dumb-jump s drag-stuff dired-quick-sort devdocs define-word column-enforce-mode clean-aindent-mode centered-cursor-mode auto-highlight-symbol ht dash auto-compile packed compat all-the-icons aggressive-indent ace-window ace-link ace-jump-helm-line helm avy popup helm-core which-key use-package pcre2el hydra lv hybrid-mode font-lock+ evil goto-chg dotenv-mode diminish bind-map bind-key async cmake-mode))
 '(pdf-view-midnight-colors ''("#655370" . "#fbf8ef"))
 '(connection-local-criteria-alist '(((:application tramp) tramp-connection-local-default-system-profile tramp-connection-local-default-shell-profile)))
 '(connection-local-profile-alist '((tramp-connection-local-darwin-ps-profile (tramp-process-attributes-ps-args "-acxww" "-o" "pid,uid,user,gid,comm=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ" "-o" "state=abcde" "-o" "ppid,pgid,sess,tty,tpgid,minflt,majflt,time,pri,nice,vsz,rss,etime,pcpu,pmem,args") (tramp-process-attributes-ps-format (pid . number) (euid . number) (user . string) (egid . number) (comm . 52) (state . 5) (ppid . number) (pgrp . number) (sess . number) (ttname . string) (tpgid . number) (minflt . number) (majflt . number) (time . tramp-ps-time) (pri . number) (nice . number) (vsize . number) (rss . number) (etime . tramp-ps-time) (pcpu . number) (pmem . number) (args))) (tramp-connection-local-busybox-ps-profile (tramp-process-attributes-ps-args "-o" "pid,user,group,comm=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ" "-o" "stat=abcde" "-o" "ppid,pgid,tty,time,nice,etime,args") (tramp-process-attributes-ps-format (pid . number) (user . string) (group . string) (comm . 52) (state . 5) (ppid . number) (pgrp . number) (ttname . string) (time . tramp-ps-time) (nice . number) (etime . tramp-ps-time) (args))) (tramp-connection-local-bsd-ps-profile (tramp-process-attributes-ps-args "-acxww" "-o" "pid,euid,user,egid,egroup,comm=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ" "-o" "state,ppid,pgid,sid,tty,tpgid,minflt,majflt,time,pri,nice,vsz,rss,etimes,pcpu,pmem,args") (tramp-process-attributes-ps-format (pid . number) (euid . number) (user . string) (egid . number) (group . string) (comm . 52) (state . string) (ppid . number) (pgrp . number) (sess . number) (ttname . string) (tpgid . number) (minflt . number) (majflt . number) (time . tramp-ps-time) (pri . number) (nice . number) (vsize . number) (rss . number) (etime . number) (pcpu . number) (pmem . number) (args))) (tramp-connection-local-default-shell-profile (shell-file-name . "/bin/sh") (shell-command-switch . "-c")) (tramp-connection-local-default-system-profile (path-separator . ":") (null-device . "/dev/null")))))

(custom-theme-set-faces
 'Custom Light
 '(default ((((class color) (min-colors 89)) (:background "#fbf8ef" :foreground "#655370"))))
 '(cursor ((((class color) (min-colors 89)) (:background "#100a14"))))
 '(ediff-current-diff-C ((((class color) (min-colors 89)) (:background "#edf1ed" :foreground "#3a81c3" :extend t))))
 '(ediff-fine-diff-A ((((class color) (min-colors 89)) (:background "#f2241f" :foreground "#fbf8ef" :extend t))))
 '(ediff-fine-diff-B ((((class color) (min-colors 89)) (:background "#67b11d" :foreground "#fbf8ef"))))
 '(helm-selection ((((class color) (min-colors 89)) (:background "#d3d3e7"))))
 '(highlight ((((class color) (min-colors 89)) (:foreground "#655370" :background "#d3d3e7"))))
 '(highlight-parentheses-highlight ((nil (:weight ultra-bold))))
 '(hl-line ((t (:extend t :background "#efeae9"))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "#fbf8ef" :background "#ba2f59"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:background "#dae6d0" :weight normal))))
 '(line-number-current-line ((((class color) (min-colors 89)) (:foreground "#655370" :background "#efeae9" :inherit line-number))))
 '(magit-diff-context-highlight ((((class color) (min-colors 89)) (:background "#efeae9" :foreground "#655370" :extend t))))
 '(magit-section-highlight ((((class color) (min-colors 89)) (:background "#efeae9" :extend t))))
 '(show-paren-match ((((class color) (min-colors 89)) (:foreground "#ba2f59" :inherit bold :underline t))))
 '(show-paren-mismatch ((((class color) (min-colors 89)) (:foreground "#e0211d" :inherit bold :underline t))))
 '(tty-menu-disabled-face ((t (:background "blue" :foreground "white" :strike-through t))))
 '(custom-button ((((class color) (min-colors 89)) :background "#efeae9" :foreground "#655370" :box (:line-width 2 :style released-button))))
 '(default-italic ((((class color) (min-colors 89)) (:italic t))))
 '(error ((((class color) (min-colors 89)) (:foreground "#e0211d"))))
 '(eval-sexp-fu-flash ((((class color) (min-colors 89)) (:background "#42ae2c" :foreground "#fbf8ef"))))
 '(eval-sexp-fu-flash-error ((((class color) (min-colors 89)) (:background "#e0211d" :foreground "#fbf8ef"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#3a81c3"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#2aa1ae" :background "#ecf3ec" :slant normal))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#4e3163"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#da8b55"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#6c3163" :inherit bold))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:inherit bold :foreground "#3a81c3" :slant normal))))
 '(font-lock-negation-char-face ((((class color) (min-colors 89)) (:foreground "#4e3163"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "#6c3163"))))
 '(font-lock-reference-face ((((class color) (min-colors 89)) (:foreground "#4e3163"))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#2d9574"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#ba2f59" :inherit bold))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#715ab1"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:foreground "#dc752f" :background "#fbf8ef"))))
 '(fringe ((((class color) (min-colors 89)) (:background "#fbf8ef" :foreground "#655370"))))
 '(header-line ((((class color) (min-colors 89)) :background "#efeae9")))
 '(link ((((class color) (min-colors 89)) (:foreground "#2aa1ae" :underline t))))
 '(link-visited ((((class color) (min-colors 89)) (:foreground "#6c4173" :underline t))))
 '(match ((((class color) (min-colors 89)) (:background "#d3d3e7" :foreground "#ba2f59"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:inherit bold :foreground "#3a81c3"))))
 '(page-break-lines ((((class color) (min-colors 89)) (:foreground "#d3d3e7"))))
 '(region ((((class color) (min-colors 89)) (:background "#d3d3e7" :extend t))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#e3dedd"))))
 '(shadow ((((class color) (min-colors 89)) (:foreground "#a094a2"))))
 '(success ((((class color) (min-colors 89)) (:foreground "#42ae2c"))))
 '(tooltip ((((class color) (min-colors 89)) (:background "#c8c6dd" :foreground "#655370" :bold nil :italic nil :underline nil))))
 '(vertical-border ((((class color) (min-colors 89)) (:foreground "#b3b9be"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#dc752f"))))
 '(widget-button-pressed ((((class color) (min-colors 89)) (:foreground "#67b11d"))))
 '(aw-leading-char-face ((((class color) (min-colors 89)) (:foreground "#6c3163" :weight bold :height 2.0 :box (:line-width 1 :color "#3a81c3" :style released-button)))))
 '(ahs-face ((((class color) (min-colors 89)) (:background "#d3d3e7"))))
 '(ahs-face-unfocused ((((class color) (min-colors 89)) (:background "#d3d3e7"))))
 '(ahs-definition-face ((((class color) (min-colors 89)) (:background "#d3d3e7"))))
 '(ahs-definition-face-unfocused ((((class color) (min-colors 89)) (:background "#d3d3e7"))))
 '(ahs-plugin-whole-buffer-face ((((class color) (min-colors 89)) (:background "#ba2f59" :foreground "#fbf8ef"))))
 '(ahs-plugin-default-face ((((class color) (min-colors 89)) (:background "#d3d3e7"))))
 '(ahs-plugin-default-face-unfocused ((((class color) (min-colors 89)) (:background "#d3d3e7"))))
 '(anzu-mode-line ((((class color) (min-colors 89)) (:foreground "#b1951d" :inherit bold))))
 '(ac-completion-face ((((class color) (min-colors 89)) (:underline t :foreground "#3a81c3"))))
 '(avy-lead-face ((((class color) (min-colors 89)) (:background "#edf2e9" :foreground "#67b11d"))))
 '(avy-lead-face-0 ((((class color) (min-colors 89)) (:background "#edf2e9" :foreground "#b1951d"))))
 '(avy-lead-face-1 ((((class color) (min-colors 89)) (:background "#edf2e9" :foreground "#a31db1"))))
 '(avy-lead-face-2 ((((class color) (min-colors 89)) (:background "#edf2e9" :foreground "#3a81c3"))))
 '(cfw:face-title ((((class color) (min-colors 89)) (:foreground "#3a81c3" :height 2.0 :weight bold :inherit variable-pitch))))
 '(cfw:face-header ((((class color) (min-colors 89)) (:foreground "#655370" :weight bold))))
 '(cfw:face-saturday ((((class color) (min-colors 89)) (:foreground "#655370" :weight bold))))
 '(cfw:face-sunday ((((class color) (min-colors 89)) (:foreground "#655370" :weight bold))))
 '(cfw:face-holiday ((((class color) (min-colors 89)) (:foreground "#3a81c3" :weight bold))))
 '(cfw:face-grid ((((class color) (min-colors 89)) (:foreground "#b3b9be"))))
 '(cfw:face-default-content ((((class color) (min-colors 89)) (:foreground "#67b11d"))))
 '(cfw:face-periods ((((class color) (min-colors 89)) (:foreground "#21b8c7"))))
 '(cfw:face-day-title ((((class color) (min-colors 89)) (:background "#edf1ed"))))
 '(cfw:face-default-day ((((class color) (min-colors 89)) (:foreground "#655370" :weight bold))))
 '(cfw:face-annotation ((((class color) (min-colors 89)) (:foreground "#2d9574"))))
 '(cfw:face-disable ((((class color) (min-colors 89)) (:foreground "#a094a2"))))
 '(cfw:face-today-title ((((class color) (min-colors 89)) (:background "#3a81c3" :weight bold))))
 '(cfw:face-today ((((class color) (min-colors 89)) (:background "#edf1ed" :weight bold))))
 '(cfw:face-select ((((class color) (min-colors 89)) (:background "#a31db1" :weight bold))))
 '(cfw:face-toolbar ((((class color) (min-colors 89)) (:foreground "#655370" :background "#fbf8ef"))))
 '(cfw:face-toolbar-button-off ((((class color) (min-colors 89)) (:foreground "#655370" :weight bold))))
 '(cfw:face-toolbar-button-on ((((class color) (min-colors 89)) (:foreground "#655370" :weight bold))))
 '(centaur-tabs-default ((((class color) (min-colors 89)) (:background "#fbf8ef" :foreground "#fbf8ef"))))
 '(centaur-tabs-selected ((((class color) (min-colors 89)) (:background "#fbf8ef" :foreground "#655370" :weight bold))))
 '(centaur-tabs-unselected ((((class color) (min-colors 89)) (:background "#efeae9" :foreground "#a094a2" :weight light))))
 '(centaur-tabs-selected-modified ((((class color) (min-colors 89)) (:background "#fbf8ef" :foreground "#3a81c3" :weight bold))))
 '(centaur-tabs-unselected-modified ((((class color) (min-colors 89)) (:background "#efeae9" :weight light :foreground "#3a81c3"))))
 '(centaur-tabs-active-bar-face ((((class color) (min-colors 89)) (:background "#3a81c3"))))
 '(centaur-tabs-modified-marker-selected ((((class color) (min-colors 89)) (:inherit 'centaur-tabs-selected :foreground "#3a81c3"))))
 '(centaur-tabs-modified-marker-unselected ((((class color) (min-colors 89)) (:inherit 'centaur-tabs-unselected :foreground "#3a81c3"))))
 '(cider-enlightened ((((class color) (min-colors 89)) (:background nil :box (:color "#b1951d" :line-width -1 :style nil) :foreground "#b1951d"))))
 '(cider-enlightened-local ((((class color) (min-colors 89)) (:foreground "#b1951d"))))
 '(cider-fringe-good-face ((((class color) (min-colors 89)) (:foreground "#42ae2c"))))
 '(cider-instrumented-face ((((class color) (min-colors 89)) (:background nil :box (:color "#f2241f" :line-width -1 :style nil) :foreground "#f2241f"))))
 '(cider-result-overlay-face ((((class color) (min-colors 89)) (:background nil :box (:color "#3a81c3" :line-width -1 :style nil) :foreground "#3a81c3"))))
 '(cider-test-error-face ((((class color) (min-colors 89)) (:background "#dc752f" :foreground "#fbf8ef"))))
 '(cider-test-failure-face ((((class color) (min-colors 89)) (:background "#e0211d" :foreground "#fbf8ef"))))
 '(cider-test-success-face ((((class color) (min-colors 89)) (:background "#42ae2c" :foreground "#fbf8ef"))))
 '(cider-traced-face ((((class color) (min-colors 89)) :box (:color "#21b8c7" :line-width -1 :style nil))))
 '(company-echo-common ((((class color) (min-colors 89)) (:background "#655370" :foreground "#fbf8ef"))))
 '(company-preview ((((class color) (min-colors 89)) (:background "#e2e0ea" :foreground "#8c799f"))))
 '(company-preview-common ((((class color) (min-colors 89)) (:background "#e2e0ea" :foreground "#655370"))))
 '(company-preview-search ((((class color) (min-colors 89)) (:inherit match))))
 '(company-tooltip-scrollbar-track ((((class color) (min-colors 89)) (:background "#efeae9"))))
 '(company-tooltip-scrollbar-thumb ((((class color) (min-colors 89)) (:background "#d3d3e7"))))
 '(company-template-field ((((class color) (min-colors 89)) (:inherit region))))
 '(company-tooltip ((((class color) (min-colors 89)) (:background "#e2e0ea" :foreground "#8c799f"))))
 '(company-tooltip-annotation ((((class color) (min-colors 89)) (:foreground "#ba2f59"))))
 '(company-tooltip-common ((((class color) (min-colors 89)) (:background "#e2e0ea" :foreground "#3a81c3"))))
 '(company-tooltip-common-selection ((((class color) (min-colors 89)) (:foreground "#3a81c3"))))
 '(company-tooltip-mouse ((((class color) (min-colors 89)) (:inherit highlight))))
 '(company-tooltip-search ((((class color) (min-colors 89)) (:inherit match))))
 '(company-tooltip-selection ((((class color) (min-colors 89)) (:background "#c8c6dd" :foreground "#655370"))))
 '(diff-added ((((class color) (min-colors 89)) :background nil :foreground "#67b11d" :extend t)))
 '(diff-changed ((((class color) (min-colors 89)) :background nil :foreground "#3a81c3")))
 '(diff-header ((((class color) (min-colors 89)) :background "#ddd8eb" :foreground "#6c3163" :extend t)))
 '(diff-file-header ((((class color) (min-colors 89)) :background "#ddd8eb" :foreground "#655370" :extend t)))
 '(diff-indicator-added ((((class color) (min-colors 89)) :background nil :foreground "#67b11d" :extend t)))
 '(diff-indicator-changed ((((class color) (min-colors 89)) :background nil :foreground "#3a81c3")))
 '(diff-indicator-removed ((((class color) (min-colors 89)) :background nil :foreground "#f2241f")))
 '(diff-refine-added ((((class color) (min-colors 89)) :background "#67b11d" :foreground "#fbf8ef")))
 '(diff-refine-changed ((((class color) (min-colors 89)) :background "#3a81c3" :foreground "#fbf8ef")))
 '(diff-refine-removed ((((class color) (min-colors 89)) :background "#f2241f" :foreground "#fbf8ef")))
 '(diff-removed ((((class color) (min-colors 89)) :background nil :foreground "#f2241f" :extend t)))
 '(diff-hl-insert ((((class color) (min-colors 89)) :background "#67b11d" :foreground "#67b11d")))
 '(diff-hl-delete ((((class color) (min-colors 89)) :background "#f2241f" :foreground "#f2241f")))
 '(diff-hl-change ((((class color) (min-colors 89)) :background "#3a81c3" :foreground "#3a81c3")))
 '(dired-directory ((((class color) (min-colors 89)) (:foreground "#3a81c3" :background "#fbf8ef" :inherit bold))))
 '(dired-flagged ((((class color) (min-colors 89)) (:foreground "#f2241f"))))
 '(dired-header ((((class color) (min-colors 89)) (:foreground "#6c4173" :inherit bold))))
 '(dired-ignored ((((class color) (min-colors 89)) (:inherit shadow))))
 '(dired-mark ((((class color) (min-colors 89)) (:foreground "#6c4173" :inherit bold))))
 '(dired-marked ((((class color) (min-colors 89)) (:foreground "#a31db1" :inherit bold))))
 '(dired-perm-write ((((class color) (min-colors 89)) (:foreground "#655370" :underline t))))
 '(dired-symlink ((((class color) (min-colors 89)) (:foreground "#21b8c7" :background "#fbf8ef" :inherit bold))))
 '(dired-warning ((((class color) (min-colors 89)) (:foreground "#dc752f"))))
 '(doom-modeline-bar ((((class color) (min-colors 89)) (:background "#3a81c3"))))
 '(ediff-current-diff-A ((((class color) (min-colors 89)) (:background "#faede4" :foreground "#f2241f" :extend t))))
 '(ediff-current-diff-Ancestor ((((class color) (min-colors 89)) (:background "#edf2e9" :foreground "#2d9574" :extend t))))
 '(ediff-current-diff-B ((((class color) (min-colors 89)) (:background "#edf2e9" :foreground "#67b11d" :extend t))))
 '(ediff-even-diff-A ((((class color) (min-colors 89)) (:background "#e3dedd" :extend t))))
 '(ediff-even-diff-Ancestor ((((class color) (min-colors 89)) (:background "#e3dedd" :extend t))))
 '(ediff-even-diff-B ((((class color) (min-colors 89)) (:background "#e3dedd" :extend t))))
 '(ediff-even-diff-C ((((class color) (min-colors 89)) (:background "#e3dedd" :extend t))))
 '(ediff-fine-diff-Ancestor ((((class color) (min-colors 89)) (:background nil :inherit bold :extend t))))
 '(ediff-fine-diff-C ((((class color) (min-colors 89)) (:background "#3a81c3" :foreground "#fbf8ef"))))
 '(ediff-odd-diff-A ((((class color) (min-colors 89)) (:background "#d2ceda" :extend t))))
 '(ediff-odd-diff-Ancestor ((((class color) (min-colors 89)) (:background "#d2ceda" :extend t))))
 '(ediff-odd-diff-B ((((class color) (min-colors 89)) (:background "#d2ceda" :extend t))))
 '(ediff-odd-diff-C ((((class color) (min-colors 89)) (:background "#d2ceda" :extend t))))
 '(ein:cell-input-area ((((class color) (min-colors 89)) (:background "#efeae9"))))
 '(ein:cell-input-prompt ((((class color) (min-colors 89)) (:foreground "#42ae2c"))))
 '(ein:cell-output-prompt ((((class color) (min-colors 89)) (:foreground "#e0211d"))))
 '(ein:notification-tab-normal ((((class color) (min-colors 89)) (:foreground "#3a81c3"))))
 '(ein:notification-tab-selected ((((class color) (min-colors 89)) (:foreground "#42ae2c" :inherit bold))))
 '(eldoc-highlight-function-argument ((((class color) (min-colors 89)) (:foreground "#ba2f59" :inherit bold))))
 '(elfeed-search-date-face ((((class color) (min-colors 89)) (:foreground "#2d9574"))))
 '(elfeed-search-feed-face ((((class color) (min-colors 89)) (:foreground "#3a81c3"))))
 '(elfeed-search-tag-face ((((class color) (min-colors 89)) (:foreground "#6c3163"))))
 '(elfeed-search-title-face ((((class color) (min-colors 89)) (:foreground "#715ab1"))))
 '(elfeed-search-unread-title-face ((((class color) (min-colors 89)) (:foreground "#655370"))))
 '(enh-ruby-op-face ((((class color) (min-colors 89)) (:background "#fbf8ef" :foreground "#655370"))))
 '(enh-ruby-string-delimiter-face ((((class color) (min-colors 89)) (:foreground "#2d9574"))))
 '(erc-input-face ((((class color) (min-colors 89)) (:foreground "#6c3163"))))
 '(erc-my-nick-face ((((class color) (min-colors 89)) (:foreground "#3a81c3"))))
 '(erc-nick-default-face ((((class color) (min-colors 89)) (:foreground "#3a81c3"))))
 '(erc-nick-prefix-face ((((class color) (min-colors 89)) (:foreground "#b1951d"))))
 '(erc-notice-face ((((class color) (min-colors 89)) (:foreground "#2d9574"))))
 '(erc-prompt-face ((((class color) (min-colors 89)) (:foreground "#ba2f59" :inherit bold))))
 '(erc-timestamp-face ((((class color) (min-colors 89)) (:foreground "#3a81c3"))))
 '(eshell-ls-archive ((((class color) (min-colors 89)) (:foreground "#f2241f" :inherit bold))))
 '(eshell-ls-backup ((((class color) (min-colors 89)) (:inherit font-lock-comment-face))))
 '(eshell-ls-clutter ((((class color) (min-colors 89)) (:inherit font-lock-comment-face))))
 '(eshell-ls-directory ((((class color) (min-colors 89)) (:foreground "#3a81c3" :inherit bold))))
 '(eshell-ls-executable ((((class color) (min-colors 89)) (:foreground "#42ae2c" :inherit bold))))
 '(eshell-ls-missing ((((class color) (min-colors 89)) (:inherit font-lock-warning-face))))
 '(eshell-ls-product ((((class color) (min-colors 89)) (:inherit font-lock-doc-face))))
 '(eshell-ls-special ((((class color) (min-colors 89)) (:foreground "#b1951d" :inherit bold))))
 '(eshell-ls-symlink ((((class color) (min-colors 89)) (:foreground "#21b8c7" :inherit bold))))
 '(eshell-ls-unreadable ((((class color) (min-colors 89)) (:foreground "#655370"))))
 '(eshell-prompt ((((class color) (min-colors 89)) (:foreground "#3a81c3" :inherit bold))))
 '(ess-assignment-face ((((class color) (min-colors 89)) (:foreground "#ba2f59" :inherit bold))))
 '(ess-backquoted-face ((((class color) (min-colors 89)) (:foreground "#715ab1"))))
 '(ess-constant-face ((((class color) (min-colors 89)) (:inherit font-lock-constant-face))))
 '(ess-f-t-face ((((class color) (min-colors 89)) (:inherit font-lock-constant-face))))
 '(ess-function-call-face ((((class color) (min-colors 89)) (:foreground "#6c3163"))))
 '(ess-keyword-face ((((class color) (min-colors 89)) (:inherit font-lock-keyword-face))))
 '(ess-matrix-face ((((class color) (min-colors 89)) (:foreground "#a094a2"))))
 '(ess-modifiers-face ((((class color) (min-colors 89)) (:foreground "#3a81c3"))))
 '(ess-numbers-face ((((class color) (min-colors 89)) (:inherit font-lock-constant-face))))
 '(ess-operator-face ((((class color) (min-colors 89)) (:foreground "#715ab1"))))
 '(ess-paren-face ((((class color) (min-colors 89)) (:foreground "#3a81c3"))))
 '(ess-r-control-flow-keyword-face ((((class color) (min-colors 89)) (:foreground "#3a81c3"))))
 '(ess-r-signal-keyword-face ((((class color) (min-colors 89)) (:foreground "#dc752f"))))
 '(evil-ex-lazy-highlight ((((class color) (min-colors 89)) (:background "#ba2f59" :foreground "#fbf8ef"))))
 '(evil-ex-substitute-matches ((((class color) (min-colors 89)) (:background "#faede4" :foreground "#f2241f"))))
 '(evil-ex-substitute-replacement ((((class color) (min-colors 89)) (:background "#edf2e9" :foreground "#67b11d"))))
 '(evil-goggles--pulse-face ((((class color) (min-colors 89)) (:background "#f6f1e1" :foreground "#b1951d"))))
 '(evil-goggles-change-face ((((class color) (min-colors 89)) (:background "#d1dcdf" :foreground "#3a81c3"))))
 '(evil-goggles-commentary-face ((((class color) (min-colors 89)) (:background "#edf2e9" :foreground "#2d9574"))))
 '(evil-goggles-delete-face ((((class color) (min-colors 89)) (:background "#eed9d2" :foreground "#f2241f"))))
 '(evil-goggles-fill-and-move-face ((((class color) (min-colors 89)) (:background "#dae6d0" :foreground "#67b11d"))))
 '(evil-goggles-indent-face ((((class color) (min-colors 89)) (:background "#dae6d0" :foreground "#67b11d"))))
 '(evil-goggles-join-face ((((class color) (min-colors 89)) (:background "#dae6d0" :foreground "#67b11d"))))
 '(evil-goggles-nerd-commenter-face ((((class color) (min-colors 89)) (:background "#edf2e9" :foreground "#2d9574"))))
 '(evil-goggles-paste-face ((((class color) (min-colors 89)) (:background "#dae6d0" :foreground "#67b11d"))))
 '(evil-goggles-record-macro-face ((((class color) (min-colors 89)) (:background "#d1dcdf" :foreground "#3a81c3"))))
 '(evil-goggles-replace-with-register-face ((((class color) (min-colors 89)) (:background "#f6f1e1" :foreground "#b1951d"))))
 '(evil-goggles-set-marker-face ((((class color) (min-colors 89)) (:background "#d1dcdf" :foreground "#3a81c3"))))
 '(evil-goggles-shift-face ((((class color) (min-colors 89)) (:background "#d1dcdf" :foreground "#3a81c3"))))
 '(evil-goggles-surround-face ((((class color) (min-colors 89)) (:background "#d1dcdf" :foreground "#3a81c3"))))
 '(evil-goggles-yank-face ((((class color) (min-colors 89)) (:background "#d1dcdf" :foreground "#3a81c3"))))
 '(evil-goggles-undo-redo-add-face ((((class color) (min-colors 89)) (:background "#dae6d0" :foreground "#67b11d"))))
 '(evil-goggles-undo-redo-change-face ((((class color) (min-colors 89)) (:background "#d1dcdf" :foreground "#3a81c3"))))
 '(evil-goggles-undo-redo-remove-face ((((class color) (min-colors 89)) (:background "#eed9d2" :foreground "#f2241f"))))
 '(evil-mc-cursor-bar-face ((((class color) (min-colors 89)) (:foreground "#2d9574"))))
 '(evil-mc-cursor-default-face ((((class color) (min-colors 89)) (:background "#2d9574" :foreground "#d2ceda"))))
 '(evil-mc-cursor-hbar-face ((((class color) (min-colors 89)) (:foreground "#2d9574"))))
 '(evil-mc-region-face ((((class color) (min-colors 89)) (:inherit highlight))))
 '(flycheck-error ((((supports :underline (:style line)) (class color) (min-colors 89)) (:underline (:style line :color "#e0211d"))) (((class color) (min-colors 89)) (:foreground "#655370" :background "#e0211d" :inherit bold :underline t))))
 '(flycheck-error-list-checker-name ((((class color) (min-colors 89)) (:foreground "#3a81c3"))))
 '(flycheck-fringe-error ((((class color) (min-colors 89)) (:foreground "#e0211d" :inherit bold))))
 '(flycheck-fringe-info ((((class color) (min-colors 89)) (:foreground "#3a81c3" :inherit bold))))
 '(flycheck-fringe-warning ((((class color) (min-colors 89)) (:foreground "#dc752f" :inherit bold))))
 '(flycheck-info ((((supports :underline (:style line)) (class color) (min-colors 89)) (:underline (:style line :color "#3a81c3"))) (((class color) (min-colors 89)) (:foreground "#655370" :background "#3a81c3" :inherit bold :underline t))))
 '(flycheck-warning ((((supports :underline (:style line)) (class color) (min-colors 89)) (:underline (:style line :color "#dc752f"))) (((class color) (min-colors 89)) (:foreground "#655370" :background "#dc752f" :inherit bold :underline t))))
 '(flymake-error ((((supports :underline (:style line)) (class color) (min-colors 89)) (:underline (:style line :color "#e0211d"))) (((class color) (min-colors 89)) (:foreground "#655370" :background "#e0211d" :inherit bold :underline t))))
 '(flymake-note ((((supports :underline (:style line)) (class color) (min-colors 89)) (:underline (:style wave :color "#3a81c3"))) (((class color) (min-colors 89)) (:foreground "#655370" :background "#3a81c3" :inherit bold :underline t))))
 '(flymake-warning ((((supports :underline (:style line)) (class color) (min-colors 89)) (:underline (:style line :color "#dc752f"))) (((class color) (min-colors 89)) (:foreground "#655370" :background "#dc752f" :inherit bold :underline t))))
 '(flyspell-incorrect ((((supports :underline (:style line)) (class color) (min-colors 89)) (:underline (:style wave :color "#dc752f"))) (((class color) (min-colors 89)) (:foreground "#655370" :background "#dc752f" :inherit bold :underline t))))
 '(flyspell-duplicate ((((supports :underline (:style line)) (class color) (min-colors 89)) (:underline (:style wave :color "#3a81c3"))) (((class color) (min-colors 89)) (:foreground "#655370" :background "#3a81c3" :inherit bold :underline t))))
 '(jabber-activity-face ((((class color) (min-colors 89)) (:inherit bold :foreground "#f2241f"))))
 '(jabber-activity-personal-face ((((class color) (min-colors 89)) (:inherit bold :foreground "#3a81c3"))))
 '(jabber-chat-error ((((class color) (min-colors 89)) (:inherit bold :foreground "#f2241f"))))
 '(jabber-chat-prompt-foreign ((((class color) (min-colors 89)) (:inherit bold :foreground "#f2241f"))))
 '(jabber-chat-prompt-local ((((class color) (min-colors 89)) (:inherit bold :foreground "#3a81c3"))))
 '(jabber-chat-prompt-system ((((class color) (min-colors 89)) (:inherit bold :foreground "#67b11d"))))
 '(jabber-chat-text-foreign ((((class color) (min-colors 89)) (:foreground "#655370"))))
 '(jabber-chat-text-local ((((class color) (min-colors 89)) (:foreground "#655370"))))
 '(jabber-rare-time-face ((((class color) (min-colors 89)) (:foreground "#67b11d"))))
 '(jabber-roster-user-away ((((class color) (min-colors 89)) (:foreground "#b1951d"))))
 '(jabber-roster-user-chatty ((((class color) (min-colors 89)) (:inherit bold :foreground "#67b11d"))))
 '(jabber-roster-user-dnd ((((class color) (min-colors 89)) (:foreground "#f2241f"))))
 '(jabber-roster-user-error ((((class color) (min-colors 89)) (:foreground "#e0211d"))))
 '(jabber-roster-user-offline ((((class color) (min-colors 89)) (:foreground "#655370"))))
 '(jabber-roster-user-online ((((class color) (min-colors 89)) (:inherit bold :foreground "#67b11d"))))
 '(jabber-roster-user-xa ((((class color) (min-colors 89)) (:foreground "#2d9574"))))
 '(git-gutter-fr:added ((((class color) (min-colors 89)) (:foreground "#67b11d" :inherit bold))))
 '(git-gutter-fr:deleted ((((class color) (min-colors 89)) (:foreground "#f2241f" :inherit bold))))
 '(git-gutter-fr:modified ((((class color) (min-colors 89)) (:foreground "#3a81c3" :inherit bold))))
 '(git-timemachine-minibuffer-detail-face ((((class color) (min-colors 89)) (:foreground "#3a81c3" :inherit bold :background "#edf1ed"))))
 '(gnus-emphasis-highlight-words ((((class color) (min-colors 89)) (:background "#42ae2c" :foreground "#fbf8ef"))))
 '(gnus-header-content ((((class color) (min-colors 89)) (:foreground "#3a81c3"))))
 '(gnus-header-from ((((class color) (min-colors 89)) (:foreground "#715ab1"))))
 '(gnus-header-name ((((class color) (min-colors 89)) (:foreground "#6c4173"))))
 '(gnus-header-subject ((((class color) (min-colors 89)) (:foreground "#6c3163" :inherit bold))))
 '(gnus-summary-cancelled ((((class color) (min-colors 89)) (:background "#dc752f" :foreground "#fbf8ef"))))
 '(guide-key/highlight-command-face ((((class color) (min-colors 89)) (:foreground "#655370"))))
 '(guide-key/key-face ((((class color) (min-colors 89)) (:foreground "#3a81c3"))))
 '(guide-key/prefix-command-face ((((class color) (min-colors 89)) (:foreground "#3a81c3" :inherit bold))))
 '(helm-bookmark-directory ((((class color) (min-colors 89)) (:inherit helm-ff-directory))))
 '(helm-bookmark-file ((((class color) (min-colors 89)) (:foreground "#655370"))))
 '(helm-bookmark-gnus ((((class color) (min-colors 89)) (:foreground "#6c4173"))))
 '(helm-bookmark-info ((((class color) (min-colors 89)) (:foreground "#6c4173"))))
 '(helm-bookmark-man ((((class color) (min-colors 89)) (:foreground "#6c4173"))))
 '(helm-bookmark-w3m ((((class color) (min-colors 89)) (:foreground "#6c4173"))))
 '(helm-buffer-directory ((((class color) (min-colors 89)) (:foreground "#655370" :background "#fbf8ef"))))
 '(helm-buffer-file ((((class color) (min-colors 89)) (:foreground "#655370" :background "#fbf8ef"))))
 '(helm-buffer-not-saved ((((class color) (min-colors 89)) (:foreground "#6c4173" :background "#fbf8ef"))))
 '(helm-buffer-process ((((class color) (min-colors 89)) (:foreground "#3a81c3" :background "#fbf8ef"))))
 '(helm-buffer-saved-out ((((class color) (min-colors 89)) (:foreground "#655370" :background "#fbf8ef"))))
 '(helm-buffer-size ((((class color) (min-colors 89)) (:foreground "#655370" :background "#fbf8ef"))))
 '(helm-candidate-number ((((class color) (min-colors 89)) (:background "#fbf8ef" :foreground "#3a81c3" :inherit bold))))
 '(helm-ff-directory ((((class color) (min-colors 89)) (:foreground "#3a81c3" :background "#fbf8ef" :inherit bold))))
 '(helm-ff-dotted-directory ((((class color) (min-colors 89)) (:foreground "#3a81c3" :background "#fbf8ef" :inherit bold))))
 '(helm-ff-dotted-symlink-directory ((((class color) (min-colors 89)) (:foreground "#21b8c7" :background "#fbf8ef" :inherit bold))))
 '(helm-ff-executable ((((class color) (min-colors 89)) (:foreground "#42ae2c" :background "#fbf8ef" :weight normal))))
 '(helm-ff-file ((((class color) (min-colors 89)) (:foreground "#655370" :background "#fbf8ef" :weight normal))))
 '(helm-ff-invalid-symlink ((((class color) (min-colors 89)) (:foreground "#f2241f" :background "#fbf8ef" :inherit bold))))
 '(helm-ff-prefix ((((class color) (min-colors 89)) (:foreground "#fbf8ef" :background "#3a81c3" :weight normal))))
 '(helm-ff-symlink ((((class color) (min-colors 89)) (:foreground "#21b8c7" :background "#fbf8ef" :inherit bold))))
 '(helm-grep-cmd-line ((((class color) (min-colors 89)) (:foreground "#655370" :background "#fbf8ef"))))
 '(helm-grep-file ((((class color) (min-colors 89)) (:foreground "#655370" :background "#fbf8ef"))))
 '(helm-grep-finish ((((class color) (min-colors 89)) (:foreground "#655370" :background "#fbf8ef"))))
 '(helm-grep-lineno ((((class color) (min-colors 89)) (:foreground "#ba2f59" :background "#fbf8ef" :inherit bold))))
 '(helm-grep-match ((((class color) (min-colors 89)) (:foreground nil :background nil :inherit helm-match))))
 '(helm-header ((((class color) (min-colors 89)) (:foreground "#655370" :background "#fbf8ef" :underline nil :box nil))))
 '(helm-header-line-left-margin ((((class color) (min-colors 89)) (:foreground "#3a81c3" :background nil))))
 '(helm-match ((((class color) (min-colors 89)) (:background "#edf1ed" :foreground "#3a81c3"))))
 '(helm-match-item ((((class color) (min-colors 89)) (:background "#edf1ed" :foreground "#3a81c3"))))
 '(helm-moccur-buffer ((((class color) (min-colors 89)) (:foreground "#715ab1" :background "#fbf8ef"))))
 '(helm-selection-line ((((class color) (min-colors 89)) (:background "#efeae9"))))
 '(helm-separator ((((class color) (min-colors 89)) (:foreground "#6c4173" :background "#fbf8ef"))))
 '(helm-source-header ((((class color) (min-colors 89)) (:background "#6c4173" :foreground "#fbf8ef" :inherit bold))))
 '(helm-time-zone-current ((((class color) (min-colors 89)) (:foreground "#3a81c3" :background "#fbf8ef"))))
 '(helm-time-zone-home ((((class color) (min-colors 89)) (:foreground "#6c4173" :background "#fbf8ef"))))
 '(helm-visible-mark ((((class color) (min-colors 89)) (:foreground "#3a81c3" :background "#e3dedd"))))
 '(helm-swoop-target-line-block-face ((((class color) (min-colors 89)) (:foreground "#655370" :background "#d3d3e7"))))
 '(helm-swoop-target-line-face ((((class color) (min-colors 89)) (:background "#d3d3e7"))))
 '(helm-swoop-target-word-face ((((class color) (min-colors 89)) (:background "#d3d3e7" :foreground "#ba2f59"))))
 '(hi-green ((((class color) (min-colors 89)) (:foreground "#67b11d" :background "#edf2e9"))))
 '(hi-yellow ((((class color) (min-colors 89)) (:foreground "#b1951d" :background "#f6f1e1"))))
 '(highlight-indentation-face ((((class color) (min-colors 89)) (:background "#ecf3ec"))))
 '(highlight-symbol-face ((((class color) (min-colors 89)) (:background "#efeae9"))))
 '(highlight-thing ((((class color) (min-colors 89)) (:background "#efeae9"))))
 '(hydra-face-blue ((((class color) (min-colors 89)) (:foreground "#3a81c3"))))
 '(hydra-face-red ((((class color) (min-colors 89)) (:foreground "#f2241f"))))
 '(ido-first-match ((((class color) (min-colors 89)) (:foreground "#6c4173" :inherit bold))))
 '(ido-only-match ((((class color) (min-colors 89)) (:foreground "#ba2f59" :inherit bold))))
 '(ido-subdir ((((class color) (min-colors 89)) (:foreground "#3a81c3"))))
 '(ido-vertical-match-face ((((class color) (min-colors 89)) (:foreground "#6c4173" :underline nil))))
 '(info-header-xref ((((class color) (min-colors 89)) (:foreground "#6c3163" :underline t))))
 '(info-menu ((((class color) (min-colors 89)) (:foreground "#42ae2c"))))
 '(info-node ((((class color) (min-colors 89)) (:foreground "#6c3163" :inherit bold))))
 '(info-quoted-name ((((class color) (min-colors 89)) (:foreground "#3a81c3"))))
 '(info-reference-item ((((class color) (min-colors 89)) (:background nil :underline t :inherit bold))))
 '(info-string ((((class color) (min-colors 89)) (:foreground "#2d9574"))))
 '(info-title-1 ((((class color) (min-colors 89)) (:height 1.4 :inherit bold))))
 '(info-title-2 ((((class color) (min-colors 89)) (:height 1.3 :inherit bold))))
 '(info-title-3 ((((class color) (min-colors 89)) (:height 1.3))))
 '(info-title-4 ((((class color) (min-colors 89)) (:height 1.2))))
 '(ivy-current-match ((((class color) (min-colors 89)) (:background "#d3d3e7" :inherit bold :extend t))))
 '(ivy-minibuffer-match-face-1 ((((class color) (min-colors 89)) (:inherit bold))))
 '(ivy-minibuffer-match-face-2 ((((class color) (min-colors 89)) (:foreground "#3a81c3" :underline t))))
 '(ivy-minibuffer-match-face-3 ((((class color) (min-colors 89)) (:foreground "#b1951d" :underline t))))
 '(ivy-minibuffer-match-face-4 ((((class color) (min-colors 89)) (:foreground "#67b11d" :underline t))))
 '(ivy-remote ((((class color) (min-colors 89)) (:foreground "#21b8c7"))))
 '(ivy-posframe ((((class color) (min-colors 89)) (:background "#e3dedd"))))
 '(font-latex-bold-face ((((class color) (min-colors 89)) (:foreground "#6c4173"))))
 '(font-latex-italic-face ((((class color) (min-colors 89)) (:foreground "#3a81c3" :italic t))))
 '(font-latex-match-reference-keywords ((((class color) (min-colors 89)) (:foreground "#4e3163"))))
 '(font-latex-match-variable-keywords ((((class color) (min-colors 89)) (:foreground "#715ab1"))))
 '(font-latex-sectioning-0-face ((((class color) (min-colors 89)) (:inherit bold :foreground "#67b11d" :height 1.3 :background nil))))
 '(font-latex-sectioning-1-face ((((class color) (min-colors 89)) (:inherit bold :foreground "#b1951d" :height 1.3 :background nil))))
 '(font-latex-sectioning-2-face ((((class color) (min-colors 89)) (:inherit bold :foreground "#3a81c3" :height 1.3 :background nil))))
 '(font-latex-sectioning-3-face ((((class color) (min-colors 89)) (:inherit bold :foreground "#2d9574" :height 1.2 :background nil))))
 '(font-latex-sectioning-4-face ((((class color) (min-colors 89)) (:bold nil :foreground "#67b11d" :height 1.1 :background nil))))
 '(font-latex-sectioning-5-face ((((class color) (min-colors 89)) (:bold nil :foreground "#b1951d" :background nil))))
 '(font-latex-string-face ((((class color) (min-colors 89)) (:foreground "#2d9574"))))
 '(font-latex-warning-face ((((class color) (min-colors 89)) (:foreground "#dc752f"))))
 '(ledger-font-directive-face ((((class color) (min-colors 89)) (:foreground "#da8b55"))))
 '(ledger-font-posting-amount-face ((((class color) (min-colors 89)) (:foreground "#b1951d"))))
 '(ledger-font-posting-date-face ((((class color) (min-colors 89)) (:foreground "#3a81c3"))))
 '(ledger-occur-xact-face ((((class color) (min-colors 89)) (:background "#efeae9"))))
 '(linum ((((class color) (min-colors 89)) (:foreground "#a8a8bf" :background "#efeae9" :inherit default))))
 '(line-number ((((class color) (min-colors 89)) (:foreground "#a8a8bf" :background "#efeae9" :inherit default))))
 '(linum-relative-current-face ((((class color) (min-colors 89)) (:foreground "#6c4173"))))
 '(lsp-ui-doc-background ((((class color) (min-colors 89)) (:background "#efeae9"))))
 '(lsp-ui-doc-header ((((class color) (min-colors 89)) (:foreground "#3a81c3" :background "#edf1ed"))))
 '(lsp-ui-sideline-code-action ((((class color) (min-colors 89)) (:foreground "#6c4173"))))
 '(magit-blame-culprit ((((class color) (min-colors 89)) :background "#f6f1e1" :foreground "#b1951d")))
 '(magit-blame-date ((((class color) (min-colors 89)) :background "#f6f1e1" :foreground "#67b11d")))
 '(magit-blame-hash ((((class color) (min-colors 89)) :background "#f6f1e1" :foreground "#6c3163")))
 '(magit-blame-header ((((class color) (min-colors 89)) :background "#f6f1e1" :foreground "#67b11d")))
 '(magit-blame-heading ((((class color) (min-colors 89)) :background "#f6f1e1" :foreground "#67b11d")))
 '(magit-blame-name ((((class color) (min-colors 89)) :background "#f6f1e1" :foreground "#b1951d")))
 '(magit-blame-sha1 ((((class color) (min-colors 89)) :background "#f6f1e1" :foreground "#6c3163")))
 '(magit-blame-subject ((((class color) (min-colors 89)) :background "#f6f1e1" :foreground "#b1951d")))
 '(magit-blame-summary ((((class color) (min-colors 89)) :background "#f6f1e1" :foreground "#b1951d" :extend t)))
 '(magit-blame-time ((((class color) (min-colors 89)) :background "#f6f1e1" :foreground "#67b11d")))
 '(magit-branch ((((class color) (min-colors 89)) (:foreground "#4e3163" :inherit bold))))
 '(magit-branch-current ((((class color) (min-colors 89)) (:background "#edf1ed" :foreground "#3a81c3" :inherit bold :box t))))
 '(magit-branch-local ((((class color) (min-colors 89)) (:background "#edf1ed" :foreground "#3a81c3" :inherit bold))))
 '(magit-branch-remote ((((class color) (min-colors 89)) (:background "#edf2e9" :foreground "#2d9574" :inherit bold))))
 '(magit-diff-hunk-heading ((((class color) (min-colors 89)) (:background "#e2e0ea" :foreground "#8c799f" :extend t))))
 '(magit-diff-hunk-heading-highlight ((((class color) (min-colors 89)) (:background "#c8c6dd" :foreground "#655370" :extend t))))
 '(magit-hash ((((class color) (min-colors 89)) (:foreground "#715ab1"))))
 '(magit-hunk-heading ((((class color) (min-colors 89)) (:background "#e3dedd" :extend t))))
 '(magit-hunk-heading-highlight ((((class color) (min-colors 89)) (:background "#e3dedd" :extend t))))
 '(magit-item-highlight ((((class color) (min-colors 89)) :background "#efeae9" :extend t)))
 '(magit-log-author ((((class color) (min-colors 89)) (:foreground "#6c3163"))))
 '(magit-log-head-label-head ((((class color) (min-colors 89)) (:background "#b1951d" :foreground "#fbf8ef" :inherit bold))))
 '(magit-log-head-label-local ((((class color) (min-colors 89)) (:background "#3a81c3" :foreground "#fbf8ef" :inherit bold))))
 '(magit-log-head-label-remote ((((class color) (min-colors 89)) (:background "#42ae2c" :foreground "#fbf8ef" :inherit bold))))
 '(magit-log-head-label-tags ((((class color) (min-colors 89)) (:background "#a31db1" :foreground "#fbf8ef" :inherit bold))))
 '(magit-log-head-label-wip ((((class color) (min-colors 89)) (:background "#21b8c7" :foreground "#fbf8ef" :inherit bold))))
 '(magit-log-sha1 ((((class color) (min-colors 89)) (:foreground "#2d9574"))))
 '(magit-process-ng ((((class color) (min-colors 89)) (:foreground "#dc752f" :inherit bold))))
 '(magit-process-ok ((((class color) (min-colors 89)) (:foreground "#6c3163" :inherit bold))))
 '(magit-reflog-amend ((((class color) (min-colors 89)) (:foreground "#a31db1"))))
 '(magit-reflog-checkout ((((class color) (min-colors 89)) (:foreground "#3a81c3"))))
 '(magit-reflog-cherry-pick ((((class color) (min-colors 89)) (:foreground "#67b11d"))))
 '(magit-reflog-commit ((((class color) (min-colors 89)) (:foreground "#67b11d"))))
 '(magit-reflog-merge ((((class color) (min-colors 89)) (:foreground "#67b11d"))))
 '(magit-reflog-other ((((class color) (min-colors 89)) (:foreground "#21b8c7"))))
 '(magit-reflog-rebase ((((class color) (min-colors 89)) (:foreground "#a31db1"))))
 '(magit-reflog-remote ((((class color) (min-colors 89)) (:foreground "#21b8c7"))))
 '(magit-reflog-reset ((((class color) (min-colors 89)) (:foreground "#f2241f"))))
 '(magit-section-heading ((((class color) (min-colors 89)) (:foreground "#3a81c3" :inherit bold :extend t))))
 '(magit-section-title ((((class color) (min-colors 89)) (:background "#fbf8ef" :foreground "#3a81c3" :inherit bold))))
 '(Man-overstrike ((((class color) (min-colors 89)) (:foreground "#3a81c3" :inherit bold))))
 '(Man-reverse ((((class color) (min-colors 89)) (:foreground "#d3d3e7"))))
 '(Man-underline ((((class color) (min-colors 89)) (:foreground "#6c4173" :underline t))))
 '(markdown-header-face-1 ((((class color) (min-colors 89)) (:inherit bold :foreground "#3a81c3" :height 1.3 :background nil))))
 '(markdown-header-face-2 ((((class color) (min-colors 89)) (:inherit bold :foreground "#2d9574" :height 1.2 :background nil))))
 '(markdown-header-face-3 ((((class color) (min-colors 89)) (:bold nil :foreground "#67b11d" :height 1.1 :background nil))))
 '(markdown-header-face-4 ((((class color) (min-colors 89)) (:bold nil :foreground "#b1951d" :background nil))))
 '(markdown-header-face-5 ((((class color) (min-colors 89)) (:bold nil :foreground "#3a81c3"))))
 '(markdown-header-face-6 ((((class color) (min-colors 89)) (:bold nil :foreground "#2d9574"))))
 '(markdown-table-face ((((class color) (min-colors 89)) (:foreground "#655370" :background "#edf1ed"))))
 '(mode-line ((((class color) (min-colors 89)) (:foreground "#655370" :background "#e7e5eb" :box (:color "#b3b9be" :line-width 1)))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:inherit bold :foreground "#6c3163"))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:foreground "#655370" :background "#fbf8ef" :box (:color "#b3b9be" :line-width 1)))))
 '(mu4e-attach-number-face ((((class color) (min-colors 89)) (:foreground "#715ab1"))))
 '(mu4e-cited-1-face ((((class color) (min-colors 89)) (:foreground "#3a81c3"))))
 '(mu4e-cited-2-face ((((class color) (min-colors 89)) (:foreground "#2d9574"))))
 '(mu4e-cited-3-face ((((class color) (min-colors 89)) (:foreground "#67b11d"))))
 '(mu4e-cited-4-face ((((class color) (min-colors 89)) (:foreground "#b1951d"))))
 '(mu4e-cited-5-face ((((class color) (min-colors 89)) (:foreground "#3a81c3"))))
 '(mu4e-cited-6-face ((((class color) (min-colors 89)) (:foreground "#2d9574"))))
 '(mu4e-cited-7-face ((((class color) (min-colors 89)) (:foreground "#67b11d"))))
 '(mu4e-contact-face ((((class color) (min-colors 89)) (:foreground "#6c3163"))))
 '(mu4e-draft-face ((((class color) (min-colors 89)) (:foreground "#715ab1"))))
 '(mu4e-flagged-face ((((class color) (min-colors 89)) (:foreground "#b1951d" :inherit bold))))
 '(mu4e-header-key-face ((((class color) (min-colors 89)) (:foreground "#da8b55" :inherit bold))))
 '(mu4e-header-title-face ((((class color) (min-colors 89)) (:foreground "#3a81c3" :inherit bold))))
 '(mu4e-header-marks-face ((((class color) (min-colors 89)) (:foreground "#6c4173"))))
 '(mu4e-header-value-face ((((class color) (min-colors 89)) (:foreground "#3a81c3" :inherit bold))))
 '(mu4e-header-highlight-face ((((class color) (min-colors 89)) (:background "#d3d3e7"))))
 '(mu4e-highlight-face ((((class color) (min-colors 89)) (:foreground "#6c4173"))))
 '(mu4e-title-face ((((class color) (min-colors 89)) (:foreground "#2d9574" :inherit bold))))
 '(mu4e-replied-face ((((class color) (min-colors 89)) (:foreground "#67b11d"))))
 '(mu4e-modeline-face ((((class color) (min-colors 89)) (:foreground "#b1951d"))))
 '(mu4e-special-header-value-face ((((class color) (min-colors 89)) (:foreground "#67b11d"))))
 '(mu4e-unread-face ((((class color) (min-colors 89)) (:foreground "#3a81c3" :inherit bold))))
 '(mu4e-view-url-number-face ((((class color) (min-colors 89)) (:foreground "#6c4173"))))
 '(mu4e-maildirs-extension-maildir-hl-face ((((class color) (min-colors 89)) (:foreground "#3a81c3" :inherit bold))))
 '(notmuch-search-date ((((class color) (min-colors 89)) (:foreground "#6c3163"))))
 '(notmuch-search-flagged-face ((((class color) (min-colors 89)) (:weight extra-bold))))
 '(notmuch-search-non-matching-authors ((((class color) (min-colors 89)) (:foreground "#a094a2"))))
 '(notmuch-search-unread-face ((((class color) (min-colors 89)) (:background "#e7e7fc"))))
 '(notmuch-tag-face ((((class color) (min-colors 89)) (:foreground "#3a81c3"))))
 '(notmuch-tag-flagged ((((class color) (min-colors 89)) (:foreground "#dc752f"))))
 '(neo-dir-link-face ((((class color) (min-colors 89)) (:foreground "#3a81c3" :inherit bold))))
 '(neo-expand-btn-face ((((class color) (min-colors 89)) (:foreground "#655370"))))
 '(neo-file-link-face ((((class color) (min-colors 89)) (:foreground "#655370"))))
 '(neo-root-dir-face ((((class color) (min-colors 89)) (:foreground "#6c3163" :inherit bold))))
 '(org-agenda-clocking ((((class color) (min-colors 89)) (:background "#d3d3e7" :foreground "#6c4173"))))
 '(org-agenda-date ((((class color) (min-colors 89)) (:foreground "#715ab1" :height 1.0))))
 '(org-agenda-date-today ((((class color) (min-colors 89)) (:foreground "#3a81c3" :inherit bold :height 1.0))))
 '(org-agenda-date-weekend ((((class color) (min-colors 89)) (:inherit bold :foreground "#715ab1"))))
 '(org-agenda-done ((((class color) (min-colors 89)) (:foreground "#42ae2c" :height 1.0))))
 '(org-agenda-structure ((((class color) (min-colors 89)) (:inherit bold :foreground "#6c4173"))))
 '(org-block ((((class color) (min-colors 89)) (:background "#e8e3f0" :foreground "#655370" :extend t))))
 '(org-block-begin-line ((((class color) (min-colors 89)) (:background "#ddd8eb" :foreground "#9380b2" :extend t))))
 '(org-block-end-line ((((class color) (min-colors 89)) (:background "#ddd8eb" :foreground "#9380b2" :extend t))))
 '(org-clock-overlay ((((class color) (min-colors 89)) (:foreground "#6c4173"))))
 '(org-code ((((class color) (min-colors 89)) (:foreground "#21b8c7"))))
 '(org-column ((((class color) (min-colors 89)) (:background "#d3d3e7" :inherit default))))
 '(org-column-title ((((class color) (min-colors 89)) (:background "#d3d3e7"))))
 '(org-date ((((class color) (min-colors 89)) (:underline t :foreground "#715ab1"))))
 '(org-date-selected ((((class color) (min-colors 89)) (:background "#6c3163" :foreground "#fbf8ef"))))
 '(org-document-info-keyword ((((class color) (min-colors 89)) (:foreground "#da8b55"))))
 '(org-document-title ((((class color) (min-colors 89)) (:foreground "#6c3163" :inherit bold :height 1.4 :underline t))))
 '(org-done ((((class color) (min-colors 89)) (:foreground "#42ae2c" :inherit bold :background "#edf2e9"))))
 '(org-ellipsis ((((class color) (min-colors 89)) (:foreground "#3a81c3"))))
 '(org-footnote ((((class color) (min-colors 89)) (:underline t :foreground "#655370"))))
 '(org-headline-done ((((class color) (min-colors 89)) (:foreground "#2d9574"))))
 '(org-headline-todo ((((class color) (min-colors 89)) (:foreground "#da8b55"))))
 '(org-hide ((((class color) (min-colors 89)) (:foreground "#655370"))))
 '(org-kbd ((((class color) (min-colors 89)) (:inherit region :foreground "#655370" :box (:line-width 1 :style released-button)))))
 '(org-level-1 ((((class color) (min-colors 89)) (:inherit bold :bold unspecified :foreground "#3a81c3" :height 1.3 :background nil))))
 '(org-level-2 ((((class color) (min-colors 89)) (:inherit bold :bold unspecified :foreground "#2d9574" :height 1.2 :background nil))))
 '(org-level-3 ((((class color) (min-colors 89)) (:bold nil :foreground "#67b11d" :height 1.1 :background nil))))
 '(org-level-4 ((((class color) (min-colors 89)) (:bold nil :foreground "#b1951d" :background nil))))
 '(org-level-5 ((((class color) (min-colors 89)) (:bold nil :foreground "#3a81c3"))))
 '(org-level-6 ((((class color) (min-colors 89)) (:bold nil :foreground "#2d9574"))))
 '(org-level-7 ((((class color) (min-colors 89)) (:bold nil :foreground "#67b11d"))))
 '(org-level-8 ((((class color) (min-colors 89)) (:bold nil :foreground "#b1951d"))))
 '(org-link ((((class color) (min-colors 89)) (:underline t :foreground "#2aa1ae"))))
 '(org-meta-line ((((class color) (min-colors 89)) (:foreground "#da8b55"))))
 '(org-mode-line-clock-overrun ((((class color) (min-colors 89)) (:foreground "#e0211d"))))
 '(org-priority ((((class color) (min-colors 89)) (:foreground "#dc752f" :inherit bold :bold unspecified))))
 '(org-quote ((((class color) (min-colors 89)) (:inherit org-block :slant italic))))
 '(org-scheduled ((((class color) (min-colors 89)) (:foreground "#6c4173"))))
 '(org-scheduled-today ((((class color) (min-colors 89)) (:foreground "#6c3163" :height 1.0))))
 '(org-scheduled-previously ((((class color) (min-colors 89)) (:foreground "#655370" :slant italic))))
 '(org-sexp-date ((((class color) (min-colors 89)) (:foreground "#655370"))))
 '(org-special-keyword ((((class color) (min-colors 89)) (:foreground "#6c3163"))))
 '(org-table ((((class color) (min-colors 89)) (:foreground "#655370" :background "#edf1ed"))))
 '(org-tag ((((class color) (min-colors 89)) (:foreground "#da8b55"))))
 '(org-time-grid ((((class color) (min-colors 89)) (:foreground "#2d9574"))))
 '(org-todo ((((class color) (min-colors 89)) (:foreground "#dc752f" :inherit bold :background "#f6f1e1"))))
 '(org-upcoming-deadline ((((class color) (min-colors 89)) (:foreground "#dc752f" :inherit org-priority))))
 '(org-upcoming-distant-deadline ((((class color) (min-colors 89)) (:foreground "#42ae2c" :inherit org-priority))))
 '(org-verbatim ((((class color) (min-colors 89)) (:foreground "#3a81c3"))))
 '(org-verse ((((class color) (min-colors 89)) (:inherit org-block :slant italic))))
 '(org-warning ((((class color) (min-colors 89)) (:foreground "#e0211d" :inherit org-priority))))
 '(outline-1 ((((class color) (min-colors 89)) (:inherit org-level-1))))
 '(outline-2 ((((class color) (min-colors 89)) (:inherit org-level-2))))
 '(outline-3 ((((class color) (min-colors 89)) (:inherit org-level-3))))
 '(outline-4 ((((class color) (min-colors 89)) (:inherit org-level-4))))
 '(outline-5 ((((class color) (min-colors 89)) (:inherit org-level-5))))
 '(outline-6 ((((class color) (min-colors 89)) (:inherit org-level-6))))
 '(outline-7 ((((class color) (min-colors 89)) (:inherit org-level-7))))
 '(outline-8 ((((class color) (min-colors 89)) (:inherit org-level-8))))
 '(parinfer-pretty-parens:dim-paren-face ((((class color) (min-colors 89)) (:foreground "#a094a2"))))
 '(parinfer-rust-dim-parens ((((class color) (min-colors 89)) (:foreground "#a094a2"))))
 '(persp-selected-face ((((class color) (min-colors 89)) (:inherit bold :foreground "#6c3163"))))
 '(popup-enu-selection-face ((((class color) (min-colors 89)) (:background "#c8c6dd" :foreground "#655370"))))
 '(popup-face ((((class color) (min-colors 89)) (:background "#e2e0ea" :foreground "#8c799f"))))
 '(popup-isearch-match ((((class color) (min-colors 89)) (:inherit match))))
 '(popup-menu-face ((((class color) (min-colors 89)) (:background "#e2e0ea" :foreground "#655370"))))
 '(popup-menu-mouse-face ((((class color) (min-colors 89)) (:inherit highlight))))
 '(popup-scroll-bar-background-face ((((class color) (min-colors 89)) (:background "#efeae9"))))
 '(popup-scroll-bar-foreground-face ((((class color) (min-colors 89)) (:background "#d3d3e7"))))
 '(popup-tip-face ((((class color) (min-colors 89)) (:background "#c8c6dd" :foreground "#655370" :bold nil :italic nil :underline nil))))
 '(powerline-active1 ((((class color) (min-colors 89)) (:background "#d3d3e7" :foreground "#655370"))))
 '(powerline-active2 ((((class color) (min-colors 89)) (:background "#d3d3e7" :foreground "#655370"))))
 '(powerline-inactive1 ((((class color) (min-colors 89)) (:background "#efeae9" :foreground "#655370"))))
 '(powerline-inactive2 ((((class color) (min-colors 89)) (:background "#efeae9" :foreground "#655370"))))
 '(rainbow-delimiters-depth-1-face ((((class color) (min-colors 89)) :foreground "#3a81c3")))
 '(rainbow-delimiters-depth-2-face ((((class color) (min-colors 89)) :foreground "#6c3163")))
 '(rainbow-delimiters-depth-3-face ((((class color) (min-colors 89)) :foreground "#2d9574")))
 '(rainbow-delimiters-depth-4-face ((((class color) (min-colors 89)) :foreground "#67b11d")))
 '(rainbow-delimiters-depth-5-face ((((class color) (min-colors 89)) :foreground "#b1951d")))
 '(rainbow-delimiters-depth-6-face ((((class color) (min-colors 89)) :foreground "#3a81c3")))
 '(rainbow-delimiters-depth-7-face ((((class color) (min-colors 89)) :foreground "#6c3163")))
 '(rainbow-delimiters-depth-8-face ((((class color) (min-colors 89)) :foreground "#2d9574")))
 '(rainbow-delimiters-mismatched-face ((((class color) (min-colors 89)) :foreground "#e0211d" :overline t)))
 '(rainbow-delimiters-unmatched-face ((((class color) (min-colors 89)) :foreground "#e0211d" :overline t)))
 '(rcirc-bright-nick ((((class color) (min-colors 89)) (:background "#edf2e9" :foreground "#21b8c7"))))
 '(rcirc-dim-nick ((((class color) (min-colors 89)) (:foreground "#a094a2"))))
 '(rcirc-keyword ((((class color) (min-colors 89)) (:background "#dae6d0" :foreground "#67b11d"))))
 '(rcirc-timestamp ((((class color) (min-colors 89)) (:foreground "#3a81c3"))))
 '(rcirc-track-keyword ((((class color) (min-colors 89)) (:background "#67b11d" :foreground "#fbf8ef"))))
 '(rcirc-url ((((class color) (min-colors 89)) (:inherit link))))
 '(sh-heredoc ((((class color) (min-colors 89)) :foreground "#2d9574")))
 '(sh-quoted-exec ((((class color) (min-colors 89)) :foreground "#6c3163")))
 '(shm-current-face ((((class color) (min-colors 89)) (:background "#dae6d0"))))
 '(shm-quarantine-face ((((class color) (min-colors 89)) (:background "#eed9d2"))))
 '(show-paren-match-expression ((((class color) (min-colors 89)) (:background "#dae6d0"))))
 '(sp-pair-overlay-face ((((class color) (min-colors 89)) (:background "#d3d3e7" :foreground nil))))
 '(sp-show-pair-match-face ((((class color) (min-colors 89)) (:foreground "#ba2f59" :inherit bold :underline t))))
 '(smerge-base ((((class color) (min-colors 89)) (:background "#f6f1e1" :extend t))))
 '(smerge-markers ((((class color) (min-colors 89)) (:background "#e2e0ea" :foreground "#8c799f" :extend t))))
 '(smerge-mine ((((class color) (min-colors 89)) (:background "#faede4"))))
 '(smerge-other ((((class color) (min-colors 89)) (:background "#edf2e9"))))
 '(smerge-refined-added ((((class color) (min-colors 89)) (:background "#dae6d0" :foreground "#67b11d"))))
 '(smerge-refined-changed ((((class color) (min-colors 89)) (:background "#d1dcdf" :foreground "#3a81c3"))))
 '(smerge-refined-removed ((((class color) (min-colors 89)) (:background "#eed9d2" :foreground "#f2241f"))))
 '(solaire-default-face ((((class color) (min-colors 89)) (:inherit default :background "#efeae9"))))
 '(solaire-minibuffer-face ((((class color) (min-colors 89)) (:inherit default :background "#efeae9"))))
 '(solaire-hl-line-face ((((class color) (min-colors 89)) (:inherit hl-line :background "#efeae9"))))
 '(solaire-org-hide-face ((((class color) (min-colors 89)) (:inherit org-hide :background "#efeae9"))))
 '(spaceline-flycheck-error ((((class color) (min-colors 89)) (:foreground "#e0211d"))))
 '(spaceline-flycheck-info ((((class color) (min-colors 89)) (:foreground "#3a81c3"))))
 '(spaceline-flycheck-warning ((((class color) (min-colors 89)) (:foreground "#dc752f"))))
 '(spaceline-python-venv ((((class color) (min-colors 89)) (:foreground "#6c4173"))))
 '(spacemacs-transient-state-title-face ((((class color) (min-colors 89)) (:background nil :foreground "#6c4173" :box nil :inherit bold))))
 '(swiper-line-face ((((class color) (min-colors 89)) (:background "#d3d3e7" :inherit bold))))
 '(swiper-match-face-1 ((((class color) (min-colors 89)) (:inherit bold))))
 '(swiper-match-face-2 ((((class color) (min-colors 89)) (:foreground "#3a81c3" :underline t))))
 '(swiper-match-face-3 ((((class color) (min-colors 89)) (:foreground "#b1951d" :underline t))))
 '(swiper-match-face-4 ((((class color) (min-colors 89)) (:foreground "#67b11d" :underline t))))
 '(tabbar-button ((((class color) (min-colors 89)) (:inherit tabbar-default))))
 '(tabbar-button-highlight ((((class color) (min-colors 89)) (:inherit tabbar-default))))
 '(tabbar-default ((((class color) (min-colors 89)) (:background "#fbf8ef" :foreground "#3a81c3" :height 0.9))))
 '(tabbar-highlight ((((class color) (min-colors 89)) (:underline t))))
 '(tabbar-selected ((((class color) (min-colors 89)) (:inherit tabbar-default :foreground "#6c3163" :weight bold))))
 '(tabbar-selected-modified ((((class color) (min-colors 89)) (:inherit tabbar-default :foreground "#f2241f" :weight bold))))
 '(tabbar-separator ((((class color) (min-colors 89)) (:inherit tabbar-default))))
 '(tabbar-unselected ((((class color) (min-colors 89)) (:inherit tabbar-default :background "#fbf8ef" :slant italic :weight light))))
 '(tabbar-unselected-modified ((((class color) (min-colors 89)) (:inherit tabbar-unselected :background "#fbf8ef" :foreground "#f2241f"))))
 '(term ((((class color) (min-colors 89)) (:foreground "#655370" :background "#fbf8ef"))))
 '(term-color-black ((((class color) (min-colors 89)) (:foreground "#d2ceda" :background "#d2ceda"))))
 '(term-color-blue ((((class color) (min-colors 89)) (:foreground "#3a81c3" :background "#3a81c3"))))
 '(term-color-cyan ((((class color) (min-colors 89)) (:foreground "#21b8c7" :background "#21b8c7"))))
 '(term-color-green ((((class color) (min-colors 89)) (:foreground "#67b11d" :background "#67b11d"))))
 '(term-color-magenta ((((class color) (min-colors 89)) (:foreground "#a31db1" :background "#a31db1"))))
 '(term-color-red ((((class color) (min-colors 89)) (:foreground "#f2241f" :background "#f2241f"))))
 '(term-color-white ((((class color) (min-colors 89)) (:foreground "#655370" :background "#655370"))))
 '(term-color-yellow ((((class color) (min-colors 89)) (:foreground "#b1951d" :background "#b1951d"))))
 '(vterm-color-default ((((class color) (min-colors 89)) (:foreground "#655370" :background "#fbf8ef"))))
 '(vterm-color-black ((((class color) (min-colors 89)) (:foreground "#d2ceda" :background "#d2ceda"))))
 '(vterm-color-blue ((((class color) (min-colors 89)) (:foreground "#3a81c3" :background "#3a81c3"))))
 '(vterm-color-cyan ((((class color) (min-colors 89)) (:foreground "#21b8c7" :background "#21b8c7"))))
 '(vterm-color-green ((((class color) (min-colors 89)) (:foreground "#67b11d" :background "#67b11d"))))
 '(vterm-color-magenta ((((class color) (min-colors 89)) (:foreground "#a31db1" :background "#a31db1"))))
 '(vterm-color-red ((((class color) (min-colors 89)) (:foreground "#f2241f" :background "#f2241f"))))
 '(vterm-color-white ((((class color) (min-colors 89)) (:foreground "#655370" :background "#655370"))))
 '(vterm-color-yellow ((((class color) (min-colors 89)) (:foreground "#b1951d" :background "#b1951d"))))
 '(tide-hl-identifier-face ((((class color) (min-colors 89)) (:foreground "#b1951d" :background "#f6f1e1"))))
 '(treemacs-git-added-face ((((class color) (min-colors 89)) (:foreground "#67b11d" :background "#edf2e9"))))
 '(treemacs-git-conflict-face ((((class color) (min-colors 89)) (:foreground "#f2241f" :background "#faede4"))))
 '(treemacs-git-ignored-face ((((class color) (min-colors 89)) (:foreground "#b1951d"))))
 '(treemacs-git-modified-face ((((class color) (min-colors 89)) (:foreground "#3a81c3" :background "#edf1ed"))))
 '(treemacs-git-untracked-face ((((class color) (min-colors 89)) (:foreground "#2d9574" :background "#edf2e9"))))
 '(tab-bar ((((class color) (min-colors 89)) (:foreground "#655370" :background "#fbf8ef"))))
 '(tab-bar-tab ((((class color) (min-colors 89)) (:foreground "#655370" :background "#fbf8ef" :weight bold))))
 '(tab-bar-tab-inactive ((((class color) (min-colors 89)) (:foreground "#a094a2" :background "#efeae9" :weight light))))
 '(tab-line ((((class color) (min-colors 89)) (:foreground "#655370" :background "#fbf8ef"))))
 '(tab-line-tab-current ((((class color) (min-colors 89)) (:foreground "#655370" :background "#fbf8ef" :weight bold))))
 '(tab-line-tab-inactive ((((class color) (min-colors 89)) (:foreground "#a094a2" :background "#efeae9" :weight light))))
 '(web-mode-builtin-face ((((class color) (min-colors 89)) (:inherit font-lock-builtin-face))))
 '(web-mode-comment-face ((((class color) (min-colors 89)) (:inherit font-lock-comment-face))))
 '(web-mode-constant-face ((((class color) (min-colors 89)) (:inherit font-lock-constant-face))))
 '(web-mode-current-element-highlight-face ((((class color) (min-colors 89)) (:background "#e3dedd"))))
 '(web-mode-doctype-face ((((class color) (min-colors 89)) (:inherit font-lock-comment-face))))
 '(web-mode-function-name-face ((((class color) (min-colors 89)) (:inherit font-lock-function-name-face))))
 '(web-mode-html-attr-name-face ((((class color) (min-colors 89)) (:foreground "#6c3163"))))
 '(web-mode-html-attr-value-face ((((class color) (min-colors 89)) (:foreground "#3a81c3"))))
 '(web-mode-html-tag-face ((((class color) (min-colors 89)) (:foreground "#3a81c3"))))
 '(web-mode-keyword-face ((((class color) (min-colors 89)) (:foreground "#3a81c3"))))
 '(web-mode-string-face ((((class color) (min-colors 89)) (:foreground "#2d9574"))))
 '(web-mode-symbol-face ((((class color) (min-colors 89)) (:foreground "#ba2f59"))))
 '(web-mode-type-face ((((class color) (min-colors 89)) (:inherit font-lock-type-face))))
 '(web-mode-warning-face ((((class color) (min-colors 89)) (:inherit font-lock-warning-face))))
 '(which-key-command-description-face ((((class color) (min-colors 89)) (:foreground "#655370"))))
 '(which-key-group-description-face ((((class color) (min-colors 89)) (:foreground "#3a81c3"))))
 '(which-key-key-face ((((class color) (min-colors 89)) (:foreground "#6c3163" :inherit bold))))
 '(which-key-separator-face ((((class color) (min-colors 89)) (:background nil :foreground "#2d9574"))))
 '(which-key-special-key-face ((((class color) (min-colors 89)) (:background "#6c3163" :foreground "#fbf8ef"))))
 '(which-func ((((class color) (min-colors 89)) (:foreground "#6c3163"))))
 '(whitespace-empty ((((class color) (min-colors 89)) (:background nil :foreground "#b1951d"))))
 '(whitespace-indentation ((((class color) (min-colors 89)) (:background nil :foreground "#dc752f"))))
 '(whitespace-line ((((class color) (min-colors 89)) (:background nil :foreground "#6c4173"))))
 '(whitespace-newline ((((class color) (min-colors 89)) (:background nil :foreground "#6c4173"))))
 '(whitespace-space ((((class color) (min-colors 89)) (:background nil :foreground "#d3d3e7"))))
 '(whitespace-space-after-tab ((((class color) (min-colors 89)) (:background nil :foreground "#b1951d"))))
 '(whitespace-space-before-tab ((((class color) (min-colors 89)) (:background nil :foreground "#b1951d"))))
 '(whitespace-tab ((((class color) (min-colors 89)) (:background nil :foreground "#d3d3e7"))))
 '(whitespace-trailing ((((class color) (min-colors 89)) (:background "#e0211d" :foreground "#dc752f"))))
 '(ffap ((((class color) (min-colors 89)) (:foreground "#655370"))))
 '(flx-highlight-face ((((class color) (min-colors 89)) (:foreground "#6c4173" :underline nil))))
 '(icompletep-determined ((((class color) (min-colors 89)) :foreground "#3a81c3")))
 '(js2-external-variable ((((class color) (min-colors 89)) (:foreground "#6c4173"))))
 '(js2-function-param ((((class color) (min-colors 89)) (:foreground "#4e3163"))))
 '(js2-jsdoc-html-tag-delimiter ((((class color) (min-colors 89)) (:foreground "#2d9574"))))
 '(js2-jsdoc-html-tag-name ((((class color) (min-colors 89)) (:foreground "#3a81c3"))))
 '(js2-jsdoc-value ((((class color) (min-colors 89)) (:foreground "#2d9574"))))
 '(js2-private-function-call ((((class color) (min-colors 89)) (:foreground "#4e3163"))))
 '(js2-private-member ((((class color) (min-colors 89)) (:foreground "#655370"))))
 '(js3-error-face ((((class color) (min-colors 89)) (:underline "#dc752f"))))
 '(js3-external-variable-face ((((class color) (min-colors 89)) (:foreground "#715ab1"))))
 '(js3-function-param-face ((((class color) (min-colors 89)) (:foreground "#3a81c3"))))
 '(js3-instance-member-face ((((class color) (min-colors 89)) (:foreground "#4e3163"))))
 '(js3-jsdoc-tag-face ((((class color) (min-colors 89)) (:foreground "#3a81c3"))))
 '(js3-warning-face ((((class color) (min-colors 89)) (:underline "#3a81c3"))))
 '(slime-repl-inputed-output-face ((((class color) (min-colors 89)) (:foreground "#6c4173"))))
 '(trailing-whitespace ((((class color) (min-colors 89)) :foreground nil :background "#e0211d")))
 '(undo-tree-visualizer-current-face ((((class color) (min-colors 89)) :foreground "#3a81c3")))
 '(undo-tree-visualizer-default-face ((((class color) (min-colors 89)) :foreground "#655370")))
 '(undo-tree-visualizer-register-face ((((class color) (min-colors 89)) :foreground "#6c4173")))
 '(undo-tree-visualizer-unmodified-face ((((class color) (min-colors 89)) :foreground "#715ab1"))))

(provide-theme 'Custom Light)
